
services:
  app:

    build: .

    container_name: yourfavhuman_app

    ports:
    - "2408:2408"

    environment:
      - ENV=development
    
    volumes:
      - .:/app
     
    restart: unless-stopped